### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zp130494mia** [dokar3/ChipTextField#98]
Bug occurs with    implementation 'androidx.compose.ui:ui:1.5.1' and   implementation 'io.github.dokar3:chiptextfield:0.6.0' downgrading to 0.5.0 vesions and 0.4.9 give no result.

FATAL EXCEPTION: main
                                                                                                    Process: com.easemble, PID: 10236
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/ui/platform/LocalSoftwareKeyboardController;
                                                                                                    	at com.dokar.chiptextfield.BasicChipTextFieldKt.BasicChipTextField-6hQAwQA(BasicChipTextField.kt:302)
                                                                                                    	at com.dokar.chiptextfield.OutlinedChipTextFieldKt.OutlinedChipTextField-oTzSxmA(OutlinedChipTextField.kt:274)
                                                                                                    	at com.dokar.chiptextfield.OutlinedChipTextFieldKt.OutlinedChipTextField-QSzSp5g(OutlinedChipTextField.kt:81)
                                                                                                    	at
                                                                                                    com.easemble.screens.setYourProfileScreen.SetYourProfileScreenKt$SetYourProfileScreen$3$2$7.invoke(SetYourProfileScreen.kt:467)
                                                                                                    	at
                                                                                                    com.easemble.screens.setYourProfileScreen.SetYourProfileScreenKt$SetYourProfileScreen$3$2$7.invoke(SetYourProfileScreen.kt:461)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.material.ExposedDropdownMenuKt.ExposedDropdownMenuBox(ExposedDropdownMenu.kt:135)

**Comment by dokar3** [comment]
Thanks for the feedback, it looks like the new artifact has no direct dependency on compose.ui, I'll try to release a fix when I have time.

**Comment by dokar3** [comment]
0.6.1 is out, it should work again, hopefully. 
https://github.com/dokar3/ChipTextField/releases/tag/v0.6.1
